# SQLite (development/test)
default_sqlite: &default_sqlite
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default_sqlite
  database: storage/development.sqlite3
test:
  <<: *default_sqlite
  database: storage/test.sqlite3
# PostgreSQL (production)
default_pg: &default_pg
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
production:
  primary:
    <<: *default_pg
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *default_pg
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default_pg
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default_pg
    url: <%= ENV["DATABASE_URL"] %>
