test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudinary:
  service: Cloudinary
  folder: <%= Rails.env %>

# （S3を使う場合だけ。今は不要ならコメントのままでOK）
# amazon:
#   service: S3
#   access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
#   secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
#   region: <%= ENV["AWS_REGION"] %>
#   bucket: <%= ENV["AWS_BUCKET"] %>
